# Generated by Django 3.0.5 on 2020-06-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200601_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='def.jpg', null=True, upload_to='profile_pics'),
        ),
    ]
