# Generated by Django 3.0.5 on 2020-06-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200601_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='def.jpg', upload_to='image_pics'),
        ),
    ]
