# Generated by Django 3.0.5 on 2020-06-02 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200601_1837'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
