# Generated by Django 3.0.5 on 2020-06-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200602_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='def.jpg', null=True, upload_to='image_pics'),
        ),
    ]
