# Generated by Django 3.0.5 on 2020-06-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20200602_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(default='def.jpg', upload_to='image_pics'),
        ),
    ]
