# Generated by Django 3.0.5 on 2020-06-03 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20200602_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default='UnKnown', on_delete=django.db.models.deletion.CASCADE, to='main.Profile'),
        ),
    ]
