# Generated by Django 3.0.5 on 2020-06-03 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
